WIP : Espace Candidat - Prévoir oubli de mot de passe
anct-cnum/portail-candidat pull request #21
Opened 2021-08-06 10:09 UTC by Ornella452

2021-08-06 14:52 UTC, loicguillois approved these changes

2021-08-06 14:52 UTC, loicguillois approved these changes

2021-08-06 16:54 UTC, squirrion requested changes
@Ornella452 Non pour la complexité de mot de passe. Il faut la même que pour le choix du mot de passe (choosePassword). il y a donc plusieurs endroits à modifier dans le fichier ForgottenPassword

2021-08-09 08:14 UTC, squirrion commented on src/components/anonymous/ForgottenPassword.js
> +  const checkComplexity = password => password.length >= 6;
@Ornella452 la regex

2021-08-09 08:15 UTC, squirrion commented on src/components/anonymous/ForgottenPassword.js
> +    if (password && confirmPassword === password && checkComplexity(password)) {
@Ornella452 checkComplexity.test(password)

2021-08-09 08:15 UTC, squirrion commented on src/components/anonymous/ForgottenPassword.js
> +                    { password && !checkComplexity(password) &&
@Ornella452 checkComplexity.test(password)

2021-08-09 08:16 UTC, squirrion commented on src/components/anonymous/ForgottenPassword.js
> +                      <span>Le mot de passe doit contenir au moins 6 caractères.</span>
@Ornella452 <div className="invalid">Le mot de passe ne correspond pas aux exigences de sécurité.</div>

2021-08-09 08:17 UTC, Ornella452 commented on src/components/anonymous/ForgottenPassword.js
> +                      <span>Le mot de passe doit contenir au moins 6 caractères.</span>
je remplace par ce message alors ?!

2021-08-09 08:22 UTC, squirrion commented on src/components/anonymous/ForgottenPassword.js
> +
@Ornella452 ajouter une phrase sur le choix de mot de passe : `<span>Celui-ci doit contenir au moins 8 caractères dont une minuscule, une majuscule, un chiffre et un caractère spécial(!@#$%^&amp;*)</span>`

2021-08-09 09:31 UTC, squirrion commented on src/components/anonymous/ForgottenPassword.js
> +  const validEmail = useSelector(state => state.motDePasseOublie.success.successResetPassword);
@Ornella452 j'ai mis un comm sur la PR associée où tu as pris la modif car ce sera pas bon en l'état

2021-08-09 09:32 UTC, Ornella452 commented on src/components/anonymous/ForgottenPassword.js
> +  const validEmail = useSelector(state => state.motDePasseOublie.success.successResetPassword);
je regarde

2021-08-09 09:35 UTC, squirrion commented on src/components/anonymous/ForgottenPassword.js
> +                    {errorPassword && <span>{errorPassword.error ? errorPassword.error :
@Ornella452 En fait il fallait laisser comme avant ici mais juste rajouté `<span>Celui-ci doit contenir au moins 8 caractères dont une minuscule, une majuscule, un chiffre et un caractère spécial(!@#$%^&amp;*)</span>`.
On peut même ajouter une vérif du role candidat : en gros : 
```
 { tokenVerified && !passwordChoosen && user?.role === 'candidat' &&
              <div>
                <div>
                  {error && <span>{error.error ? error.error : 'Une erreur s\'est produite'}</span>}
                </div>
                <span>Celui-ci doit contenir au moins 8 caractères dont une minuscule, une majuscule, un chiffre et un caractère spécial(!@#$%^&amp;*)</span>
```

2021-08-09 09:38 UTC, Ornella452 commented on src/components/anonymous/ForgottenPassword.js
> +                    {errorPassword && <span>{errorPassword.error ? errorPassword.error :
ha ok , j'ai mal compris ...je rectif 👍

2021-08-09 10:03 UTC, Ornella452 commented on src/components/anonymous/ForgottenPassword.js
> +                    {errorPassword && <span>{errorPassword.error ? errorPassword.error :
![image](https://user-images.githubusercontent.com/68587983/128690203-b5b40008-c1de-4c6e-b62a-fa583525cacb.png)

2021-08-09 10:04 UTC, Ornella452 commented on src/components/anonymous/ForgottenPassword.js
> +                    {errorPassword && <span>{errorPassword.error ? errorPassword.error :
du coup ça rend ça, ok pour toi  👍  ?

2021-08-09 10:08 UTC, squirrion commented on src/components/anonymous/ForgottenPassword.js
> +  const validEmail = useSelector(state => state.motDePasseOublie.success.successResetPassword);
du coup ici on laisse que success

2021-08-09 10:10 UTC, squirrion commented on src/reducers/motDePasseOublieReducer.js
> +        success: action.response
@Ornella452 et ici ce sera success: action.response.successResetPassword

2021-08-09 10:10 UTC, squirrion commented on src/components/anonymous/ForgottenPassword.js
> +                    {errorPassword && <span>{errorPassword.error ? errorPassword.error :
yes nickel

2021-08-09 10:15 UTC, squirrion approved these changes

2021-08-09 10:34 UTC, MorganP-projects approved these changes

2021-08-09 12:38 UTC, merged