security fix
anct-cnum/portail-candidat pull request #65
Opened 2022-03-11 13:13 UTC by loicguillois

2022-03-11 13:14 UTC, marc-gavanier approved these changes

2022-03-11 13:23 UTC, MorganP-projects approved these changes

2022-03-11 15:27 UTC, squirrion commented on package.json
> +    "react-scripts": "^5.0.0",
pas d'impact ?

2022-03-11 16:18 UTC, loicguillois commented on package.json
> +    "react-scripts": "^5.0.0",
c'est listé ici : https://github.com/facebook/create-react-app/blob/main/CHANGELOG.md

2022-03-14 08:29 UTC, squirrion approved these changes

2022-03-16 11:54 UTC, squirrion requested changes
Je la bloque car on aura un ajustement à faire comme pour le portail-conseiller : le passage en 5.0 a des impact sur le dotenv notamment

2022-03-17 08:48 UTC, MorganP-projects approved these changes

2022-03-17 09:06 UTC, merged